### ISSUE TITLE
Svagare färgmarkering på delete och block

### ISSUE THREAD

**Issue by Ainali** [fluffis/VandalFighter#1]
Raderna med delete och block är väldigt väl markerade och drar till sig blicken oerhört väl, vilket är onödigt eftersom att det inte är dessa som man scannar efter i VandalFighter. Jag föreslår att de tunnas ut avsevärt, kanske till #ffffe0 respektive #ffb5c5.

**Comment by fluffis** [comment]
Detta projekt är inte FluffVandalFighter utan bara en kopia på gamla VandalFighter, av historiska skäl. Jag lägger till dig i rätt projekt.
